# Generated by Django 4.2.1 on 2023-07-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Text', models.TextField(max_length=300)),
                ('Image', models.ImageField(default='a.png', upload_to='image/')),
                ('Video', models.FileField(null=True, upload_to='video/', verbose_name='')),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
