# Generated by Django 4.2.1 on 2023-07-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMT', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'BlogData'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_date',
        ),
    ]
